trigger: none

pool:
  name: $(VM_IMAGE_AGENT)

stages:
  - stage: HelloWorld
    dependsOn: []
    jobs:
      - job: hello_world
        steps:
          - checkout: self
            displayName: 'Checkout'
          - script: |
              echo "Hello World!"
            displayName: 'hello'

  - stage: Deploy
    dependsOn: HelloWorld
    jobs:
      - job: deploy_k8s
        steps:
          - task: KubernetesManifest@0
            displayName: Deploy
            inputs:
              kubernetesServiceConnection: AKS-SERVICE-CONN
              namespace: default
              manifests: |
                manifests/deployment-dev.yml
                manifests/service.yml
              containers: |
                nginx:latest
