trigger: none

pool:
  name: $(VM_IMAGE_AGENT)

stages:
  - stage: HelloWorld
    dependsOn: []
    jobs:
      - job: hello_world
        steps:
          - checkout: self
            displayName: 'Checkout'
          - script: |
              echo "Hello World!"
            displayName: 'hello'
